services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4
    ports:
      - "80:80"
    # environment:
    #   VITE_API_BASE_URL: "http://localhost:3000/api"
    networks:
      - app-network
    # volumes:
    #   - ../nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4
    #
    environment:
      DATABASE_URL: postgres://admin:6e5AH311gavT72E2@db:5432/photoclub
      JWT_SECRET: kycb
    command: >
      sh -c "
      npx prisma migrate dev &&
      npm run start:prod"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 6e5AH311gavT72E2
      POSTGRES_DB: photoclub
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: