services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4
    ports:
      - "80:80"
    # environment:
    #   VITE_API_BASE_URL: "http://localhost:3000/api"
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    # dns:
    #   - 8.8.8.8
    #   - 8.8.4.4
    command: >
      sh -c "
      npx prisma migrate deploy &&
      npm run start:prod"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://admin:admin@db:5432/photoclub
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: photoclub
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: