name: Deploy Application to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies and build frontend
        run: |
          cd frontend
          npm install
          npm run build-only
          # Скопировать собранные файлы для использования в Dockerfile
          cp -r dist ../frontend-dist

      - name: Install dependencies and build backend
        run: |
          cd backend
          npm install
          npx prisma generate
          npm run build
          # Скопировать готовые файлы для использования в Dockerfile
          cp -r dist ../backend-dist

      - name: Deploy application with Docker Compose
        run: |
          # Перейти в директорию с проектом
          pwd
          cd frontend-dist
          ls
          cd ../frontend-dist
          cd backend-dist
          ls
          cd ../
          ls

          # Обновить код с ветки main
          # git pull origin main

          # Перенести собранные файлы в нужные места
          # cp -r frontend-dist/* frontend/dist
          # cp -r backend-dist/* backend/dist

          # Собрать и запустить контейнеры
          # docker-compose down
          # docker-compose up -d --build
