name: Deploy Application to Server

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Clean directory
        run: |
          cd /home/photoclub/
          rm -rf *

      - name: Copy files
        run: |
          cp -r /home/actions-runner/_work/photo-club/photo-club/* /home/photoclub/

      - name: Deploy application with Docker Compose
        run: |
          # Собрать и запустить контейнеры
          cd /home/photoclub
          docker compose down
          docker compose up -d --build
